//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webdmsEntities : DbContext
    {
        public webdmsEntities()
            : base("name=webdmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bas_comodities> bas_comodities { get; set; }
        public virtual DbSet<bas_comoditiestype> bas_comoditiestype { get; set; }
        public virtual DbSet<bas_customer> bas_customer { get; set; }
        public virtual DbSet<bas_supplier> bas_supplier { get; set; }
        public virtual DbSet<sys_application> sys_application { get; set; }
        public virtual DbSet<sys_button> sys_button { get; set; }
        public virtual DbSet<sys_dept> sys_dept { get; set; }
        public virtual DbSet<sys_dictionarydata> sys_dictionarydata { get; set; }
        public virtual DbSet<sys_menu> sys_menu { get; set; }
        public virtual DbSet<sys_operatelog> sys_operatelog { get; set; }
        public virtual DbSet<sys_region> sys_region { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_rolemenu> sys_rolemenu { get; set; }
        public virtual DbSet<sys_templates> sys_templates { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sys_userrole> sys_userrole { get; set; }
        public virtual DbSet<sys_usertype> sys_usertype { get; set; }
        public virtual DbSet<view_customer> view_customer { get; set; }
        public virtual DbSet<view_dept> view_dept { get; set; }
        public virtual DbSet<view_menu> view_menu { get; set; }
        public virtual DbSet<view_region> view_region { get; set; }
        public virtual DbSet<view_role> view_role { get; set; }
        public virtual DbSet<view_user> view_user { get; set; }
    }
}
