//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_itemprice
    {
        public System.DateTime TimeStamp { get; set; }
        public int CorpID { get; set; }
        public int SuppCustID { get; set; }
        public int ItemID { get; set; }
        public int UomID { get; set; }
        public decimal LastPrice { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int TargetType { get; set; }
    }
}
