//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_item
    {
        public System.DateTime TimeStamp { get; set; }
        public long ItemID { get; set; }
        public int CorpID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string HelperCode { get; set; }
        public string Barcode { get; set; }
        public int ItemGroupID { get; set; }
        public Nullable<int> ItemCategoryID { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<float> SaveInventory { get; set; }
        public int BaseUOM { get; set; }
        public Nullable<int> SalesUOM { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<int> PurchaseUOM { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<float> Length { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> CrossWeigth { get; set; }
        public Nullable<float> Size { get; set; }
        public float LastCost { get; set; }
        public long IsBatch { get; set; }
        public long IsForSale { get; set; }
        public long IsValid { get; set; }
        public long IsZeroValue { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public Nullable<int> CloseUserID { get; set; }
    }
}
