//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_item_picture
    {
        public System.DateTime TimeStamp { get; set; }
        public long PicID { get; set; }
        public int CorpID { get; set; }
        public int ItemID { get; set; }
        public string Picture { get; set; }
        public long Type { get; set; }
        public long IsTitle { get; set; }
        public long IsValid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
    }
}
