//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_log_userlogin
    {
        public System.DateTime TimeStamp { get; set; }
        public long UserLoginID { get; set; }
        public int CorpID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public int ComputerIP { get; set; }
        public string ComputerName { get; set; }
        public string DeviceMAC { get; set; }
        public string DeviceIMEI { get; set; }
        public string APPver { get; set; }
        public string APPpackage { get; set; }
        public string Remark { get; set; }
    }
}
