//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_purchase_invoice
    {
        public System.DateTime TimeStamp { get; set; }
        public long InvoiceID { get; set; }
        public int CorpID { get; set; }
        public string Code { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public long InvoiceType { get; set; }
        public int SupplierID { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal Amount { get; set; }
        public decimal OperAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public Nullable<long> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<int> ConfirmUserID { get; set; }
    }
}
