//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_stock_check
    {
        public System.DateTime TimeStamp { get; set; }
        public int CorpID { get; set; }
        public string Code { get; set; }
        public System.DateTime CheckDate { get; set; }
        public int RowID { get; set; }
        public int WarehouseID { get; set; }
        public int BinID { get; set; }
        public string Batch { get; set; }
        public int UomID { get; set; }
        public float StockQty { get; set; }
        public float ActQty { get; set; }
        public float AdjQty { get; set; }
        public int PrintNumber { get; set; }
        public int CheckUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long Status { get; set; }
        public string Remark { get; set; }
    }
}
