//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sys_modulebutton
    {
        public System.DateTime TimeStamp { get; set; }
        public long ModButtonID { get; set; }
        public int CorpID { get; set; }
        public int ModuleID { get; set; }
        public int ButtonID { get; set; }
        public string Name { get; set; }
        public long IsValid { get; set; }
        public long IsVisible { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    }
}
