//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_warehouse_receipt_detail
    {
        public System.DateTime TimeStamp { get; set; }
        public int CorpID { get; set; }
        public int ReceiptID { get; set; }
        public int RowID { get; set; }
        public int ItemID { get; set; }
        public int UomID { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> BinID { get; set; }
        public float BillQty { get; set; }
        public float ReceiptQty { get; set; }
        public Nullable<float> BalanceQty { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ReturnReasonID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> ProduceDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
