//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_customer
    {
        public long CustID { get; set; }
        public int CorpID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string HelperCode { get; set; }
        public string Tel { get; set; }
        public string Contact { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public long IsValid { get; set; }
        public string CustCategoryName { get; set; }
        public string regionName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<long> RegionID { get; set; }
        public string regionCode { get; set; }
        public string ParentCode { get; set; }
    }
}
