//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_warehouse
    {
        public string Address { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public string Code { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Name { get; set; }
        public long IsValid { get; set; }
        public string CloseUser { get; set; }
        public string Tel { get; set; }
        public int CorpID { get; set; }
        public long WarehouseID { get; set; }
        public Nullable<long> isRole { get; set; }
    }
}
