//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_purchase_detail
    {
        public int CorpID { get; set; }
        public int POID { get; set; }
        public int RowID { get; set; }
        public int ItemID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int UomID { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> BinID { get; set; }
        public int BillQty { get; set; }
        public int OperQty { get; set; }
        public Nullable<int> BalanceQty { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ReturnReasonID { get; set; }
        public Nullable<long> IsFree { get; set; }
        public Nullable<long> IsGift { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    }
}
