//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dept
    {
        public int DeptID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string ModifyDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<long> isRole { get; set; }
        public string Comment { get; set; }
    }
}
