//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_item_category
    {
        public string Code { get; set; }
        public int CorpID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public long IsSystem { get; set; }
        public long IsValid { get; set; }
        public int ItemGroupID { get; set; }
        public long ItemCategoryID { get; set; }
        public string Name { get; set; }
        public string ParentName { get; set; }
        public string GroupName { get; set; }
        public string CategoryName { get; set; }
        public string Remark { get; set; }
        public int Sequence { get; set; }
        public Nullable<System.DateTime> UPdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<long> isRole { get; set; }
        public long ItemType { get; set; }
    }
}
